// Minecraft-inspired pixel pets. Each sprite is an 8x8 grid (Minecraft's own
// head-texture resolution) - some a touch larger - drawn as crisp SVG pixels by
// components/Critter.jsx. `pal` maps each character to a colour; '.'/' ' = empty.
export const PETS = {
  creeper: {
    pal: { g: '#6cbb3c', G: '#57a02f', d: '#3a4a22' },
    rows: [
      'gGgGgGgG',
      'GddGGddG',
      'gddGGddg',
      'gGGddGGg',
      'gGddddGg',
      'gGddddGg',
      'gGdGGdGg',
      'gGgGgGgG',
    ],
  },
  pig: {
    pal: { p: '#eaa0aa', s: '#d77f8b', n: '#8f4f59', k: '#2a1a1e' },
    rows: [
      '.pppppp.',
      'pppppppp',
      'pkpppkpp',
      'pppppppp',
      'pssssssp',
      'psnssnsp',
      'pssssssp',
      '.pppppp.',
    ],
  },
  cow: {
    pal: { b: '#5a4632', w: '#efe9dd', k: '#241712', m: '#d6a6a0', h: '#cabfa8' },
    rows: [
      'h.bbbb.h',
      '.wbbbbw.',
      'bbkbbkbb',
      'bbbbbbbb',
      '.mmmmmm.',
      '.mkmmkm.',
      '.mmmmmm.',
      '..mmmm..',
    ],
  },
  chicken: {
    pal: { w: '#f3f3f3', W: '#d8d8d8', o: '#e8a23a', r: '#d63b3b', k: '#222222' },
    rows: [
      '...rr...',
      '..wwww..',
      '.wwwwww.',
      '.wkwwkw.',
      '.wwwwww.',
      '..oooo..',
      '..Woow..',
      '...rr...',
    ],
  },
  bee: {
    pal: { y: '#f5c542', k: '#3a2e16', w: '#ffffff', e: '#222222' },
    rows: [
      '..yyyy..',
      '.yeyyey.',
      '.kkkkkk.',
      'wyyyyyyw',
      'wkkkkkkw',
      '.yyyyyy.',
      '.kkkkkk.',
      '..yyyy..',
    ],
  },
  wolf: {
    pal: { g: '#9aa0a6', G: '#6f767c', w: '#e9ecef', k: '#1c1c1c' },
    rows: [
      'G.gggg.G',
      'GggggggG',
      'gkggggkg',
      'gggwwggg',
      'ggwwwwgg',
      'ggwkkwgg',
      '.gwwwwg.',
      '..wwww..',
    ],
  },
  polarbear: {
    pal: { w: '#f2f2ee', W: '#d6d6d0', k: '#262626' },
    rows: [
      'W.wwww.W',
      'wwwwwwww',
      'wkwwwwkw',
      'wwwwwwww',
      'wwwwwwww',
      'wwwkkwww',
      '.wwwwww.',
      '..wwww..',
    ],
  },
  enderman: {
    pal: { k: '#0c0c12', K: '#1b1b26', m: '#cd6cf0' },
    rows: [
      '..kkkk..',
      '.kKKKKk.',
      'kKKKKKKk',
      'kmmkkmmk',
      'kmmkkmmk',
      'kKKKKKKk',
      '.kKKKKk.',
      '..kkkk..',
    ],
  },
  slime: {
    pal: { g: '#6ec64a', G: '#54a838', d: '#3a5a25' },
    rows: [
      'gggggggg',
      'gGGGGGGg',
      'gGdGGdGg',
      'gGGGGGGg',
      'gGGGGGGg',
      'gGdddGGg',
      'gGGGGGGg',
      'gggggggg',
    ],
  },
  axolotl: {
    pal: { p: '#f3b6cf', P: '#e988b6', k: '#3a2a30', w: '#ffffff' },
    rows: [
      'P.pppp.P',
      'P.pppp.P',
      'PkppppkP',
      '.pppppp.',
      '.pppppp.',
      '.pwppwp.',
      '.pppppp.',
      '..pppp..',
    ],
  },
  diamond: {
    pal: { c: '#4fd6d6', l: '#b6f5f2', o: '#2c8f95' },
    rows: [
      '..oooo..',
      '.ollllo.',
      'ollccllo',
      'olclcclo',
      'olcccclo',
      '.occcco.',
      '..occo..',
      '...oo...',
    ],
  },
  enderdragon: {
    pal: { k: '#16121f', K: '#26203a', m: '#a24cff', e: '#d8a8ff', w: '#e6e0ee' },
    rows: [
      '....kk....',
      '...kkkk.k.',
      '..kKKKkkk.',
      '.kKKKKKk..',
      'kKemKKKk..',
      'kKemKKKkk.',
      'kKKKKKKk..',
      '.wwwwwk...',
      '..kkkk....',
      '...kk.....',
    ],
  },
}
